
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Users/Olivier/source/repos/Compilers/LLVM/bin/clang.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is Clang, found in:
        C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/3.26.4/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Users/Olivier/source/repos/Compilers/LLVM/bin/clang++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is Clang, found in:
        C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/3.26.4/CompilerIdCXX/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-ose53v"
      binary: "C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-ose53v"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-O0 -g -Xclang -gcodeview"
      CMAKE_EXE_LINKER_FLAGS: ""
      VCPKG_APPLOCAL_DEPS: "ON"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "C:/Users/Olivier/source/repos/CppLibraries/vcpkg"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-ose53v
        
        Run Build Command(s):C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/ninja/win/x64/ninja.exe -v cmTC_2e346 && [1/2] C:\\Users\\Olivier\\source\\repos\\Compilers\\LLVM\\bin\\clang.exe   -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -MD -MT CMakeFiles/cmTC_2e346.dir/CMakeCCompilerABI.c.obj -MF CMakeFiles\\cmTC_2e346.dir\\CMakeCCompilerABI.c.obj.d -o CMakeFiles/cmTC_2e346.dir/CMakeCCompilerABI.c.obj -c "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeCCompilerABI.c"
        [2/2] cmd.exe /C "cd . && C:\\Users\\Olivier\\source\\repos\\Compilers\\LLVM\\bin\\clang.exe -fuse-ld=lld-link -nostartfiles -nostdlib -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -Xlinker /subsystem:console CMakeFiles/cmTC_2e346.dir/CMakeCCompilerABI.c.obj -o cmTC_2e346.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_2e346.lib -Xlinker /pdb:cmTC_2e346.pdb -Xlinker /version:0.0     && cmd.exe /C "cd /D C:\\Users\\Olivier\\source\\repos\\Sae\\2nd_grade\\Module1\\PhysicsEngine\\cmake-build-debug-system\\CMakeFiles\\CMakeScratch\\TryCompile-ose53v && C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noprofile -executionpolicy Bypass -file C:/Users/Olivier/source/repos/CppLibraries/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-ose53v/cmTC_2e346.exe -installedDir C:/Users/Olivier/source/repos/CppLibraries/vcpkg/installed/x64-windows/debug/bin -OutVariable out""
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-bvetmj"
      binary: "C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-bvetmj"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-O0 -g -Xclang -gcodeview"
      CMAKE_EXE_LINKER_FLAGS: ""
      VCPKG_APPLOCAL_DEPS: "ON"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "C:/Users/Olivier/source/repos/CppLibraries/vcpkg"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-bvetmj
        
        Run Build Command(s):C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/ninja/win/x64/ninja.exe -v cmTC_2513b && [1/2] C:\\Users\\Olivier\\source\\repos\\Compilers\\LLVM\\bin\\clang++.exe   -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -MD -MT CMakeFiles/cmTC_2513b.dir/CMakeCXXCompilerABI.cpp.obj -MF CMakeFiles\\cmTC_2513b.dir\\CMakeCXXCompilerABI.cpp.obj.d -o CMakeFiles/cmTC_2513b.dir/CMakeCXXCompilerABI.cpp.obj -c "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeCXXCompilerABI.cpp"
        [2/2] cmd.exe /C "cd . && C:\\Users\\Olivier\\source\\repos\\Compilers\\LLVM\\bin\\clang++.exe -fuse-ld=lld-link -nostartfiles -nostdlib -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -Xlinker /subsystem:console CMakeFiles/cmTC_2513b.dir/CMakeCXXCompilerABI.cpp.obj -o cmTC_2513b.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_2513b.lib -Xlinker /pdb:cmTC_2513b.pdb -Xlinker /version:0.0     && cmd.exe /C "cd /D C:\\Users\\Olivier\\source\\repos\\Sae\\2nd_grade\\Module1\\PhysicsEngine\\cmake-build-debug-system\\CMakeFiles\\CMakeScratch\\TryCompile-bvetmj && C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noprofile -executionpolicy Bypass -file C:/Users/Olivier/source/repos/CppLibraries/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-bvetmj/cmTC_2513b.exe -installedDir C:/Users/Olivier/source/repos/CppLibraries/vcpkg/installed/x64-windows/debug/bin -OutVariable out""
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/Internal/FeatureTesting.cmake:34 (try_compile)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/Internal/FeatureTesting.cmake:83 (_record_compiler_features)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/Compiler/CMakeCommonCompilerMacros.cmake:121 (_record_compiler_features_cxx)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompileFeatures.cmake:70 (cmake_record_cxx_compile_features)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:70 (CMAKE_DETERMINE_COMPILE_FEATURES)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compile features"
    directories:
      source: "C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-k10ers"
      binary: "C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-k10ers"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-O0 -g -Xclang -gcodeview"
      CMAKE_EXE_LINKER_FLAGS: ""
      VCPKG_APPLOCAL_DEPS: "ON"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "C:/Users/Olivier/source/repos/CppLibraries/vcpkg"
    buildResult:
      variable: "CMAKE_CXX_FEATURE_TEST"
      cached: true
      stdout: |
        Change Dir: C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-k10ers
        
        Run Build Command(s):C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/ninja/win/x64/ninja.exe -v cmTC_8cc60 && [1/2] C:\\Users\\Olivier\\source\\repos\\Compilers\\LLVM\\bin\\clang++.exe   -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd   -std=c++14 -MD -MT CMakeFiles/cmTC_8cc60.dir/feature_tests.cxx.obj -MF CMakeFiles\\cmTC_8cc60.dir\\feature_tests.cxx.obj.d -o CMakeFiles/cmTC_8cc60.dir/feature_tests.cxx.obj -c C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-k10ers/feature_tests.cxx
        [2/2] cmd.exe /C "cd . && C:\\Users\\Olivier\\source\\repos\\Compilers\\LLVM\\bin\\clang++.exe -fuse-ld=lld-link -nostartfiles -nostdlib -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -Xlinker /subsystem:console CMakeFiles/cmTC_8cc60.dir/feature_tests.cxx.obj -o cmTC_8cc60.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_8cc60.lib -Xlinker /pdb:cmTC_8cc60.pdb -Xlinker /version:0.0   -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames  && cmd.exe /C "cd /D C:\\Users\\Olivier\\source\\repos\\Sae\\2nd_grade\\Module1\\PhysicsEngine\\cmake-build-debug-system\\CMakeFiles\\CMakeScratch\\TryCompile-k10ers && C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noprofile -executionpolicy Bypass -file C:/Users/Olivier/source/repos/CppLibraries/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-k10ers/cmTC_8cc60.exe -installedDir C:/Users/Olivier/source/repos/CppLibraries/vcpkg/installed/x64-windows/debug/bin -OutVariable out""
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/Internal/FeatureTesting.cmake:34 (try_compile)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/Internal/FeatureTesting.cmake:83 (_record_compiler_features)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/Compiler/CMakeCommonCompilerMacros.cmake:129 (_record_compiler_features_cxx)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompileFeatures.cmake:70 (cmake_record_cxx_compile_features)"
      - "C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:70 (CMAKE_DETERMINE_COMPILE_FEATURES)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compile features"
    directories:
      source: "C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-you85x"
      binary: "C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-you85x"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-O0 -g -Xclang -gcodeview"
      CMAKE_EXE_LINKER_FLAGS: ""
      VCPKG_APPLOCAL_DEPS: "ON"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "C:/Users/Olivier/source/repos/CppLibraries/vcpkg"
    buildResult:
      variable: "CMAKE_CXX_FEATURE_TEST"
      cached: true
      stdout: |
        Change Dir: C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-you85x
        
        Run Build Command(s):C:/Users/Olivier/source/repos/IDE/CLion 2023.2.1/bin/ninja/win/x64/ninja.exe -v cmTC_821a6 && [1/2] C:\\Users\\Olivier\\source\\repos\\Compilers\\LLVM\\bin\\clang++.exe   -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd   -std=c++14 -MD -MT CMakeFiles/cmTC_821a6.dir/feature_tests.cxx.obj -MF CMakeFiles\\cmTC_821a6.dir\\feature_tests.cxx.obj.d -o CMakeFiles/cmTC_821a6.dir/feature_tests.cxx.obj -c C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-you85x/feature_tests.cxx
        [2/2] cmd.exe /C "cd . && C:\\Users\\Olivier\\source\\repos\\Compilers\\LLVM\\bin\\clang++.exe -fuse-ld=lld-link -nostartfiles -nostdlib -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -Xlinker /subsystem:console CMakeFiles/cmTC_821a6.dir/feature_tests.cxx.obj -o cmTC_821a6.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_821a6.lib -Xlinker /pdb:cmTC_821a6.pdb -Xlinker /version:0.0   -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames  && cmd.exe /C "cd /D C:\\Users\\Olivier\\source\\repos\\Sae\\2nd_grade\\Module1\\PhysicsEngine\\cmake-build-debug-system\\CMakeFiles\\CMakeScratch\\TryCompile-you85x && C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noprofile -executionpolicy Bypass -file C:/Users/Olivier/source/repos/CppLibraries/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/Olivier/source/repos/Sae/2nd_grade/Module1/PhysicsEngine/cmake-build-debug-system/CMakeFiles/CMakeScratch/TryCompile-you85x/cmTC_821a6.exe -installedDir C:/Users/Olivier/source/repos/CppLibraries/vcpkg/installed/x64-windows/debug/bin -OutVariable out""
        
      exitCode: 0
...
